
import os
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt
from rich.table import Table

from tui.interaction_logger import get_interaction_logger

app = typer.Typer(
    help="Memento-S Agent TUI",
    rich_markup_mode="rich",
)
console = Console()



def get_env_file_path() -> Path:
    return Path(__file__).parent.parent / ".env"


def _env_var_for_api_key(provider: str) -> str:
    return {
        "anthropic": "ANTHROPIC_API_KEY",
        "openrouter": "OPENROUTER_API_KEY",
        "openai": "LLM_API_KEY",
    }.get(provider, "LLM_API_KEY")



def check_and_configure_api() -> bool:
    from tui.config import settings

    has_api_key = bool(settings.resolve_llm_api_key())

    get_interaction_logger().event(
        "api_config_check",
        llm_api=settings.llm_api,
        has_api_key=has_api_key,
    )

    if has_api_key:
        return True

    console.print(Panel.fit(
        "[bold red]No API configuration found![/bold red]\n\n"
        "Memento-S requires an LLM API to function.\n"
        "Let's set it up now.",
        title="Configuration Required",
    ))

    return configure_api_interactive()


def configure_api_interactive() -> bool:
    log = get_interaction_logger()
    log.event("api_config_wizard_start")

    console.print("\n[bold cyan]Select your LLM API provider:[/bold cyan]")
    console.print("  1) Anthropic (Claude API)")
    console.print("  2) OpenRouter")
    console.print("  3) Custom OpenAI-compatible API")
    console.print()

    choice = Prompt.ask("Enter choice", choices=["1", "2", "3"], default="1")
    log.event("api_config_provider_choice", choice=choice)

    env_content = "# Memento-S LLM Configuration\n# Generated by memento run\n\n"
    api_key_env_var = "LLM_API_KEY"

    if choice == "1":
        api_key = Prompt.ask("[cyan]Enter your Anthropic API Key[/cyan]", password=True)
        if not api_key:
            console.print("[red]API key is required![/red]")
            log.event("api_config_missing_key", provider="anthropic")
            return False
        model = Prompt.ask(
            "[cyan]Enter model name[/cyan]",
            default="claude-sonnet-4-20250514",
        )
        log.event("api_config_entered", provider="anthropic", model=model, api_key_len=len(api_key))
        api_key_env_var = "ANTHROPIC_API_KEY"
        env_content += (
            f"LLM_API=anthropic\n"
            f"ANTHROPIC_API_KEY={api_key}\n"
            f"LLM_MODEL={model}\n"
        )

    elif choice == "2":
        api_key = Prompt.ask("[cyan]Enter your OpenRouter API Key[/cyan]", password=True)
        if not api_key:
            console.print("[red]API key is required![/red]")
            log.event("api_config_missing_key", provider="openrouter")
            return False
        model = Prompt.ask(
            "[cyan]Enter model name[/cyan]",
            default="anthropic/claude-3.5-sonnet",
        )
        log.event("api_config_entered", provider="openrouter", model=model, api_key_len=len(api_key))
        api_key_env_var = "OPENROUTER_API_KEY"
        env_content += (
            f"LLM_API=openrouter\n"
            f"OPENROUTER_API_KEY={api_key}\n"
            f"OPENROUTER_BASE_URL=https://openrouter.ai/api/v1\n"
            f"LLM_MODEL={model}\n"
        )

    else:  # choice == "3" — custom OpenAI-compatible
        api_key = Prompt.ask("[cyan]Enter your API Key[/cyan]", password=True)
        if not api_key:
            console.print("[red]API key is required![/red]")
            log.event("api_config_missing_key", provider="custom_openai_compat")
            return False
        base_url = Prompt.ask("[cyan]Enter Base URL[/cyan]")
        if not base_url:
            console.print("[red]Base URL is required![/red]")
            log.event("api_config_missing_base_url")
            return False
        model = Prompt.ask("[cyan]Enter model name[/cyan]")
        if not model:
            console.print("[red]Model name is required![/red]")
            log.event("api_config_missing_model")
            return False
        log.event(
            "api_config_entered",
            provider="custom_openai_compat",
            base_url=base_url,
            model=model,
            api_key_len=len(api_key),
        )
        api_key_env_var = "LLM_API_KEY"
        env_content += (
            f"LLM_API=openai\n"
            f"LLM_API_KEY={api_key}\n"
            f"LLM_BASE_URL={base_url}\n"
            f"LLM_MODEL={model}\n"
        )

    env_content += (
        "\n"
        "LLM_MAX_TOKENS=100000\n"
        "LLM_TIMEOUT=120\n"
        "\n"
        "# Context management\n"
        "CONTEXT_MAX_TOKENS=80000\n"
        "CONTEXT_COMPRESS_THRESHOLD=60000\n"
        "SUMMARY_MAX_TOKENS=2000\n"
        "\n"
        "# Workspace\n"
        "WORKSPACE_DIR=./workspace\n"
    )

    console.print("\n[dim]SerpAPI is used for web search (optional)[/dim]")
    serpapi_key = Prompt.ask(
        "[cyan]Enter SerpAPI Key[/cyan] (press Enter to skip)",
        default="",
        password=True,
    )
    if serpapi_key:
        log.event("serpapi_key_entered", serpapi_key_len=len(serpapi_key))
        env_content += f"\n# SerpAPI for web search\nSERPAPI_API_KEY={serpapi_key}\n"
    else:
        log.event("serpapi_key_skipped")

    env_path = get_env_file_path()
    try:
        env_path.write_text(env_content)
        console.print(f"\n[green]Configuration saved to {env_path}[/green]")
        log.event("api_config_saved", env_path=str(env_path))

        from dotenv import load_dotenv
        load_dotenv(env_path, override=True)

        os.environ[api_key_env_var] = api_key

        log.event("api_config_wizard_done", ok=True)
        return True
    except Exception as e:
        console.print(f"[red]Failed to save configuration: {e}[/red]")
        log.exception("api_config_wizard_done", ok=False, error=str(e))
        return False



@app.command()
def run(
    create_on_miss: bool = typer.Option(
        True,
        "--create-on-miss/--no-create-on-miss",
        help="Auto-create a new skill via skill-creator when routing finds no match.",
    ),
    reload_every_turn: bool = typer.Option(
        True,
        "--reload-every-turn/--no-reload-every-turn",
        help="Reload skills after every user turn (no restart needed for newly created skills).",
    ),
    optimize_on_error: bool = typer.Option(
        True,
        "--optimize-on-error/--no-optimize-on-error",
        help="Auto-optimize a skill via skill-creator when it fails with ops/format errors.",
    ),
    optimize_attempts: int = typer.Option(
        1,
        "--optimize-attempts",
        min=0,
        max=5,
        help="Max optimization attempts per failing step (0 disables).",
    ),
):
    get_interaction_logger().event(
        "tui_run_command",
        create_on_miss=create_on_miss,
        reload_every_turn=reload_every_turn,
        optimize_on_error=optimize_on_error,
        optimize_attempts=optimize_attempts,
    )

    if not check_and_configure_api():
        console.print("[red]Cannot start without valid API configuration.[/red]")
        raise typer.Exit(1)

    from tui.app import MementoSApp
    tui_app = MementoSApp(
        create_on_miss=create_on_miss,
        reload_every_turn=reload_every_turn,
        optimize_on_error=optimize_on_error,
        optimize_attempts=optimize_attempts,
    )
    tui_app.run()


@app.command()
def doctor():
    from tui.config import settings

    get_interaction_logger().event("doctor_command")
    console.print("[bold yellow]Diagnosing environment...[/bold yellow]")

    table = Table(title="System Status")
    table.add_column("Component", style="cyan")
    table.add_column("Status", style="magenta")

    ws_status = "OK" if settings.workspace.exists() else "Missing"
    table.add_row("Workspace", ws_status)
    table.add_row("LLM API", settings.llm_api)

    table.add_row("Model", settings.llm_model)
    resolved_base = settings.resolve_llm_base_url() or "(default)"
    table.add_row("Base URL", resolved_base)
    key_status = "Set" if settings.resolve_llm_api_key() else "Missing"
    table.add_row("API Key", key_status)
    table.add_row("Max Tokens", str(settings.llm_max_tokens))
    table.add_row("Context Threshold", str(settings.context_compress_threshold))

    console.print(table)
    console.print(f"\n[grey]Workspace: {settings.workspace}[/grey]")


@app.command()
def config():
    from tui.config import settings

    get_interaction_logger().event("config_command")
    config_data = settings.model_dump()

    _sensitive_keys = [
        "llm_api_key", "anthropic_api_key", "openai_api_key",
        "openrouter_api_key", "google_api_key",
    ]
    for key in _sensitive_keys:
        if config_data.get(key):
            config_data[key] = config_data[key][:8] + "..."

    console.print(Panel.fit(str(config_data), title="Current Configuration"))


@app.command()
def chat(message: str = typer.Argument(None, help="Message to send")):
    from tui.llm_client import chat_completions

    if not message:
        console.print("[red]Please provide a message[/red]")
        raise typer.Exit(1)

    get_interaction_logger().event("chat_command", message=message, message_len=len(message))
    console.print(f"[blue]You:[/blue] {message}")
    console.print("[cyan]Memento-S:[/cyan] ", end="")

    try:
        response = chat_completions(
            "You are Memento-S, an intelligent assistant. Be concise.",
            [{"role": "user", "content": message}],
        )
        console.print(response)
        get_interaction_logger().event(
            "chat_command_response",
            response=response,
            response_len=len(response),
        )
    except Exception as e:
        console.print(f"[red]Error: {e}[/red]")
        get_interaction_logger().exception("chat_command_error", error=str(e))
        raise typer.Exit(1)


@app.command()
def history():
    from tui.config import settings
    from core.agent import SessionManager
    from tui.conversation_store import ConversationStore

    get_interaction_logger().event("history_command")
    store = ConversationStore(SessionManager())
    summaries = store.list_all()

    if not summaries:
        console.print("[yellow]No saved conversations found.[/yellow]")
        console.print(f"[dim]Conversations are stored in: {settings.conversations_path}[/dim]")
        return

    groups = store.group_by_time_period(summaries)
    idx = 1
    for group_label, group_summaries in groups:
        table = Table(title=group_label, show_header=(idx == 1))
        table.add_column("#", style="dim", width=4)
        table.add_column("Title", style="cyan", max_width=30)
        table.add_column("Msgs", style="magenta", justify="right", width=5)
        table.add_column("Model", style="dim")
        table.add_column("ID", style="dim")

        for s in group_summaries:
            table.add_row(
                str(idx),
                s.title,
                str(s.message_count),
                s.model or "-",
                s.id,
            )
            idx += 1

        console.print(table)

    console.print(f"\n[dim]Total: {len(summaries)} conversations | Storage: {settings.conversations_path}[/dim]")


if __name__ == "__main__":
    app()
